### ISSUE TITLE
2.6下安装报错

### ISSUE THREAD

**Issue by yishenggudou** [andelf/pyqqweibo#3]
你好
这个2.7下安装没问题
2.6下32位linux报错
root@ip-1111111:~# pip install pyqqweibo
Downloading/unpacking pyqqweibo
  Downloading pyqqweibo-0.3.7.tar.gz
  Running setup.py egg_info for package pyqqweibo
    Traceback (most recent call last):
      File "<string>", line 13, in <module>
      File "/root/build/pyqqweibo/setup.py", line 13, in <module>
        from qqweibo import version
      File "/root/build/pyqqweibo/qqweibo/**init**.py", line 7, in <module>
        from qqweibo.auth import OAuthHandler
      File "/root/build/pyqqweibo/qqweibo/auth.py", line 11, in <module>
        from qqweibo.api import API
      File "/root/build/pyqqweibo/qqweibo/api.py", line 16, in <module>
        class API(object):
      File "/root/build/pyqqweibo/qqweibo/api.py", line 44, in API
        require_auth = True
      File "/root/build/pyqqweibo/qqweibo/binder.py", line 217, in bind_api
        rettype)
    ValueError: zero length field name in format
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 13, in <module>

  File "/root/build/pyqqweibo/setup.py", line 13, in <module>

```
from qqweibo import version
```

  File "/root/build/pyqqweibo/qqweibo/**init**.py", line 7, in <module>

```
from qqweibo.auth import OAuthHandler
```

  File "/root/build/pyqqweibo/qqweibo/auth.py", line 11, in <module>

```
from qqweibo.api import API
```

  File "/root/build/pyqqweibo/qqweibo/api.py", line 16, in <module>

```
class API(object):
```

  File "/root/build/pyqqweibo/qqweibo/api.py", line 44, in API

```
require_auth = True
```

  File "/root/build/pyqqweibo/qqweibo/binder.py", line 217, in bind_api

```
rettype)
```

ValueError: zero length field name in format

---

Command python setup.py egg_info failed with error code 1
Storing complete log in ./pip-log.txt

**Comment by yishenggudou** [comment]
Call API Method {:s}
    ({:s}) => {:s}""".format(config['path'],
                             ', '.join(config.get('allowed_param', [])),
                             rettype)
改 {:s} 为%s  ok  {：s}是2.7的方法马？

**Comment by andelf** [comment]
最近回家了，等回去查看下问题，谢谢你

On Saturday, July 9, 2011, yishenggudou
reply@reply.github.com
wrote:

**Comment by yishenggudou** [comment]
呵呵  没事
不是什么大问题
回家还回复 辛苦你啦

**Comment by yishenggudou** [comment]
顺便再报一个
文档中
add 发表一条微博
参数: (content_, clientip_, jing, wei)
返回: RetId

> api.add(）
> 应该为api.tweet.add  吧

**Comment by andelf** [comment]
笔误，哈哈

-----原始信息-----
来自: yishenggudou reply@reply.github.com
收件人： andelf@gmail.com
已发送: 2011 7月, 周日, 10 14:25:52 格林尼治标准时间+0000
主题: Re: [pyqqweibo] 2.6下安装报错 (#3)

顺便再报一个
文档中
add 发表一条微博
参数: (content_, clientip_, jing, wei)
返回: RetId

> api.add(）
> 应该为api.tweet.add  吧

##

**Comment by benjaminsims** [comment]
Hi, sorry I don't speak Chinese but... is there a fix for this error? I also cannot install on 2.6. Thanks

**Comment by benjaminsims** [comment]
Sorry, I now realise that this is fixed in the latest version. I wonder if the PyPy package could also be updated to ease automated deployment?

Thanks for a great library

**Comment by andelf** [comment]
hi,

 I've updated the package version to 0.3.8 and uploaded to pypi.

 you can easy_install -U it now. :)

 I am using PyPy environment too. you can make a developmemt env by:

 $ virtualenv -p pypy /path/to/pypyenv --prompt='(pypy)'

 then source /path/to/pypyenv/bin/activate.

2011/11/1 Benjamin Sims <
reply@reply.github.com>

**Comment by andelf** [comment]
@benjaminsims as above~
